const temperatures = {
    Mercury: "Mercury is about 36 million miles (57 million kilometers) from the Sun. From this distance, it takes sunlight about three minutes to travel to Mercury. Even though it’s sitting right next to the Sun – relatively speaking – Mercury gets extremely cold at night. It has a mean surface temperature of 333°F (167°C). Daytime temperatures get much hotter than the mean, and can reach highs of 800°F (430°C). But without an atmosphere thick enough to hold in the heat at night, temperatures can dip as low as -290°F (-180°C).",
    Venus: "Venus is the second closest planet to the Sun after Mercury, with an average distance from the Sun of about 67 million miles (108 million kilometers). It takes sunlight about six minutes to travel to Venus. Venus also is Earth’s closest neighbor and is similar in size. It has even been called Earth’s twin. But Venus is shrouded in clouds and has a dense atmosphere that acts as a greenhouse and heats the surface to above the melting point of lead. It has a mean surface temperature of 867°F (464°C). So Venus – not Mercury – is the hottest planet in our solar system. Save that bit of info for any future trivia contests.",
    Earth: "Earth is an average of 93 million miles (150 million kilometers) from the Sun. It takes about eight minutes for light from the Sun to reach our planet. Our homeworld is a dynamic and stormy planet with everything from clear, sunny days, to brief rain showers, to tornados, to raging hurricanes, to blizzards, and dust storms. But in spite of its wide variety of storms – Earth generally has very hospitable temperatures compared to the other planets. The mean surface temperature on Earth is 59°F (15°C). But Earth days have some extreme temperatures. According to NOAA, Death Valley holds the record for the world’s highest surface air temperature ever recorded on Earth: 134°F (56.7°C) observed at Furnace Creek (Greenland Ranch), California, on July 10, 1913. Earth’s lowest recorded temperature was -128.6°F (-89.2°C) at Vostok Station, Antarctica, on July 21, 1983, according to the World Meteorological Organization.",
    Mars: "Mars is an average distance of 142 million miles (228 million kilometers) from the Sun. From this distance, it takes about 13 minutes for light to travel from the Sun to Mars. The median surface temperature on Mars is -85°F (-65°C). Because the atmosphere is so thin, heat from the Sun easily escapes Mars. Temperatures on the Red Planet range from the 70s°F (20s°C) to -225°F (-153°C). Occasionally, winds on Mars are strong enough to create dust storms that cover much of the planet. After such storms, it can be months before all of the dust settles. The ground temperature around the Perseverance rover ranges from about -136°F to 62°F (-93°C to 17°C). The air temperature near the surface ranges from about  -118°F to 8°F (-83°C to -13°C).",
    Jupiter: "Jupiter's stripes and swirls are beautiful, but they are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. The planet’s iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years. The mean temperature on Jupiter is -166°F (-110°C). Jupiter is an average distance of 484 million miles (778 million kilometers) from the Sun. From this distance, it takes sunlight 43 minutes to travel from the Sun to Jupiter. Jupiter has the shortest day in the solar system. One day on Jupiter takes only about 10 hours (the time it takes for Jupiter to rotate or spin around once), and Jupiter makes a complete orbit around the Sun (a year in Jovian time) in about 12 Earth years (4,333 Earth days). Jupiter’s equator is tilted with respect to its orbital path around the Sun by just 3 degrees. This means the giant planet spins nearly upright and does not have seasons as extreme as other planets do.",
    Saturn: "Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium and it doesn’t have a true surface. The mean temperature is -220°F (-140°C). In addition to the bone-chilling cold, the winds in the upper atmosphere of Saturn reach 1,600 feet per second (500 meters per second) in the equatorial region. In contrast, the strongest hurricane-force winds on Earth top out at about 360 feet per second (110 meters per second). And the pressure – the same kind you feel when you dive deep underwater – is so powerful it squeezes gas into a liquid.",
    Uranus: "The seventh planet from the Sun with the third largest diameter in our solar system, Uranus is very cold and windy. It has a mean temperature of  -320°F (-195°C). Uranus rotates at a nearly 90-degree angle from the plane of its orbit. This unique tilt makes Uranus appear to spin sideways, orbiting the Sun like a rolling ball. And like Saturn, Uranus has rings. The ice giant is surrounded by 13 faint rings and 27 small moons. Now we move on to the last major planet in our solar system – Neptune. What’s the weather like there? Well you would definitely need a windbreaker if you went for a visit. Dark, cold, and whipped by supersonic winds, giant Neptune is the eighth and most distant major planet orbiting our Sun. The mean temperature on Neptune is -330°F (-200°C). And not to be outdone by Jupiter and its Great Red Spot, Neptune has the Great Dark Spot – and Scooter. Yep, Scooter.",
    Neptune: "This photograph of Neptune was created from two images taken by NASA’s Voyager 2 spacecraft in August 1989. It was the first and last time a spacecraft came close to Neptune. The image shows three of the features that Voyager 2 monitored. At the north (top) is the Great Dark Spot, accompanied by bright, white clouds that undergo rapid changes in appearance. To the south of the Great Dark Spot is the bright, triangular-shaped feature that Voyager scientists nicknamed 'Scooter.' Still farther south is the feature called 'Dark Spot 2,' which has a bright core. More than 30 times as far from the Sun as Earth, Neptune is not visible to the naked eye. In 2011, Neptune completed its first 165-year orbit of the Sun since its discovery. That wraps up forecasting for the major planets."
}

export default function PlanetTemperature({currentPage}) {
    return (
        <section className="w-1/3 relative h-screen">
            <div className="w-full absolute top-3/10">
                <h1 className="text-xl font-medium">Temperature</h1>
                <p className="text-[8px] opacity-40 uppercase tracking-[0.2em]">{temperatures[currentPage]}</p>
            </div>
        </section>
    );
}